name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    name: Build TestSuite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Submodules
        run: git submodule update --init --recursive

      - name: Cache TestSuite
        id: cache-test-suite
        uses: actions/cache@v3
        with:
          path: ./build/fiu-tests
          key: ${{ runner.os }}-build-test-suite-${{ hashFiles('./tests/**/*.cpp') }}-${{ hashFiles('./tests/**/*.h') }}

      - if: ${{ steps.cache-test-suite.outputs.cache-hit != 'true' }}
        name: Build and Cache TestSuite
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B ./build ./tests
          cmake --build ./build --target=fiu-tests --config Release

  unit-tests:
    needs: build-test
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optimizationLevel: [0,1,2]
        debugLevel: [0,1,2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Submodules
        run: git submodule update --init --recursive

      - name: Cache TestSuite
        id: cache-test-suite
        uses: actions/cache@v3
        with:
          path: ./build/fiu-tests
          key: ${{ runner.os }}-build-test-suite-${{ hashFiles('./tests/**/*.cpp') }}-${{ hashFiles('./tests/**/*.h') }}
      
      - if: ${{ steps.cache-test-suite.outputs.cache-hit != 'true' }}
        name: Validate Cache
        run: |
          echo "TestSuite build cache not found. Exiting..."
          exit 1

      - name: Run Tests (O${{ matrix.optimizationLevel }}, D${{ matrix.debugLevel }})
        run: |
          ./build/fiu-tests -O${{ matrix.optimizationLevel }} -D${{ matrix.debugLevel }} -C0
      - name: Run Tests (O${{ matrix.optimizationLevel }}, D${{ matrix.debugLevel }}) Coverage 1
        run: |
          ./build/fiu-tests -O${{ matrix.optimizationLevel }} -D${{ matrix.debugLevel }} -C1
      - name: Run Tests (O${{ matrix.optimizationLevel }}, D${{ matrix.debugLevel }}) Coverage 2
        run: |
          ./build/fiu-tests -O${{ matrix.optimizationLevel }} -D${{ matrix.debugLevel }} -C2
